### ISSUE TITLE
Submission - Using API

### ISSUE THREAD

**Issue by RichardOwen2** [pmb-community/JS-Promise#1]
Berikut adalah tugas akhir yang harus diselesaikan oleh peserta bootcamp. Berikut adalah deskripsi tugasnya dan skala penilaian yang diusulkan:

Deskripsi Tugas:
Membuat aplikasi dengan API yang sudah ditentukan

Kriteria :
```TS
1. Dapat menampilkan data dengan API
2. Dapat mengubah data dalam web sesuai request
3. Memaksimalkan penggunaan API (Minimal 2)
```

API yang bisa digunakan :
Sangat Sulit :
NotesAPI : https://notes-api.dicoding.dev/v1
ForumAPI : https://forum-api.dicoding.dev/v1

Sulit :
BooksAPI : https://books-api.dicoding.dev
TheMovieDB : https://www.themoviedb.org/documentation/api

Standart :
TheSportDB : https://www.thesportsdb.com/api.php
TheMealDB : https://www.themealdb.com/api.php
TheCockTailDB : https://www.thecocktaildb.com/api.php
ZodiakAPI : https://aztro.readthedocs.io/en/latest/
RandomUserAPI : https://randomuser.me

Sangatt Mudah :
RandomPict : https://picsum.photos/
RandomJokes : https://v2.jokeapi.dev/joke/Any
ChuckNorrisJokes : https://api.chucknorris.io/
RandomAdvice : https://api.adviceslip.com/advice

Deadline :
Deadline tugas ini adalah 1 July 2023

Skala Penilaian :
```TS
1. Fungsionalitas (70+ Poin)
    - Semua Kriteria terpenuhi
    - Penilaian berdasarkan API yang digunakan
      Sangat Sulit > Langsung Sempurna jika website dapat berfungsi sesuai dengan tujuan API
      Sulit > Langsung Sempurna jika website menggunakan hampir semua Kekuatan API
      Standar > Ya standar
      Sangat Mudah > Maksimal 50 Poin
2. Tampilan (30 Poin)
    - Tampilan website yang baik lebih dapat dipercaya oleh pengguna
```

Format Pengumpulan:
Pengumpulan dari tugas ini ada 2 link yaitu link repo proyek dan link website yang sudah di hosting menggunakan github pages. Untuk tutorial hosting proyek menggunakan github pages ada pada link ini https://youtu.be/rgDDWhQe-ow.

**Comment by Dillaayh** [comment]
dilla_1131
repo : https://github.com/Dillaayh/Dillaayh.github.io.git
host : https://dillaayh.github.io/

**Comment by Mocfigh** [comment]
Arifia_1161
repo : https://github.com/Mocfigh/Mocfigh.JSprom.github.io.git
host : https://mocfigh.github.io/Mocfigh.JSprom.github.io/

**Comment by dionp3** [comment]
Dion Prayoga_11221058
Repo : https://github.com/dionp3/dionp3.github.io.git
Host : https://dionp3.github.io/

**Comment by Fadilatao** [comment]
Hadad Fadilah 11221029

Host
https://fadil-tao.github.io/
Rep
https://github.com/Fadil-Tao/Fadil-Tao.github.io

**Comment by reno99986** [comment]
Reno_11221051
repo : https://github.com/reno99986/lastsub
Host : https://reno99986.github.io/lastsub/

**Comment by iqbalfhrzii** [comment]
Iqbal Fahrozi
repo : https://github.com/iqbaalr/iqbaalr.github.io
host : https://iqbaalr.github.io

**Comment by SyifaMaulida18** [comment]
Syifa Maulida-11221007
repo : https://github.com/SyifaMaulida18/SyifaMaulida18_UsingAPI.git
host : https://syifamaulida18.github.io/SyifaMaulida18_UsingAPI/

maaf kak atas keterlambatan mengumpulkan tugas ini

**Comment by Wiraproject** [comment]
Wiranto - 11221030
repo : https://github.com/Wiraproject/Wiraproject.github.io
host : https://Wiraproject.github.io

maaf kak saya terlambat mengumpulkan, tadi malam mau saya selesaikan tapi malah ketiduran 🙏🙏🙏

**Comment by zayfitri** [comment]
Isnaini - 11221072
repo : https://github.com/zayfitri/zayfitri.github.io
host : https://zayfitri.github.io/ 

mohon maaf kak atas keterlambatannya

**Comment by ihsaan15** [comment]
Muamnar Ihsan - 11221053
Repo : https://github.com/beruanglaut115/subm-mov
Host : https://beruanglaut115.github.io/subm-mov/

**Comment by halannn** [comment]
Hairul Irawan - 11221043
Repo : https://github.com/halannn/API-Testing
Host : https://halannn.github.io/API-Testing/

Note : Maaf telat & sangat sederhana kak, dikarenakan diri ini sepertinya terkena burn out untuk coding :(

**Comment by desssti06** [comment]
desti - 11221033
host : https://desssti06.github.io/using-API/
repo : https://github.com/desssti06/using-API

**Comment by Aozora09** [comment]
Azhari - 11221019
Host : https://aozora09.github.io/
Repo : https://github.com/Aozora09/Aozora09.github.io

すみません
